import "./globals.css";
import { Inter, Chivo, Kanit } from "next/font/google";
import Link from "next/link";
import Header from "./components/header/Header";
import Nav from "./components/nav/page";
import Footer from "./components/footer/page";
import ViewCounterRoute from "./components/viewcounter/viewcounter";

const inter = Inter({ subsets: ["latin"] });
const chivo = Chivo({ subsets: ["latin"] });
const kanit = Kanit({ subsets: ["latin"], weight: "100" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={chivo.className}>
        <Header />
        <Nav />
        <ViewCounterRoute />

        {/* <nav>
          <li>
            <Link href="/">Home</Link>
            <Link href="/lab">Lab</Link>
          </li>
        </nav> */}

        {children}
        <Footer />
      </body>
    </html>
  );
}
